version: "3.9"

services:
  db:
    image: mysql:8.0
    container_name: currency_db
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: currency_manager
    ports:
      - "3307:3306"
    volumes:
      - mysql_data:/var/lib/mysql
      - ./db/schema.sql:/docker-entrypoint-initdb.d/schema.sql

  app:
    build: .
    container_name: currency_app
    depends_on:
      - db
    environment:
      DB_HOST: db
      DB_PORT: 3306
      DB_USER: root
      DB_PASSWORD: root
      DB_NAME: currency_manager
    volumes:
      - .:/app
    stdin_open: true
    tty: true

volumes:
  mysql_data: